import { allRules } from '../rules/index.js';
import { groupByRootCause } from './engine.js';

const escapePipes = (value) => String(value).replace(/\|/g, '\\|');

const evidenceBlock = (evidence) =>
  Object.entries(evidence)
    .filter(([, value]) => value !== null && value !== undefined && value !== '')
    .map(([key, value]) => `  ${key}: ${Array.isArray(value) ? value.join(' -> ') : value}`)
    .join('\n');

// Renders DEFECT_REPORT.md from a reconciliation result.
export const renderDefectReport = (result) => {
  const { summary, defects, observations, model } = result;
  const lines = [];

  lines.push('# Defect Report - OMS to Analytics sync');
  lines.push('');
  lines.push(`Generated by \`npm run reconcile -- --write-report\` at ${model.now.toISOString()}.`);
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  const lateDeliveries = observations.filter((o) => o.ruleId === 'LATE-DELIVERY').length;
  const defectCases = new Set(defects.flatMap((d) => d.cases));
  const staleCases = observations.filter((o) => o.ruleId === 'STALE-LAST-MODIFIED').flatMap((o) => o.cases);
  const corroborated = staleCases.filter((id) => defectCases.has(id));
  const unexplained = staleCases.filter((id) => !defectCases.has(id));

  lines.push(`| Source | ${model.counts.orders} orders |`);
  lines.push(`| Target | ${model.counts.events} events across ${model.counts.cases} orders |`);
  lines.push(
    `| Rules | ${summary.ruleCount} executed, ${summary.rulesTriggered} triggered, ${summary.rulesPassed} passed, ${summary.rulesErrored} errors |`,
  );
  lines.push(
    `| Defects | **${summary.distinctDefects} orders with defects** (${summary.ruleViolations} findings - some orders break more than one rule) |`,
  );
  lines.push(
    `| Severity | ${Object.entries(summary.bySeverity).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'} |`,
  );
  lines.push(
    `| Observations | ${lateDeliveries} late deliveries (not defects - the copy is correct, the delivery was slow) |`,
  );
  lines.push(
    `| Suspicious | ${unexplained.length} orders with an event after the OMS LastModified (${unexplained.join(', ') || 'none'}) - not in the contract, to be confirmed |`,
  );
  lines.push('');
  // Per-dimension counts are findings, not distinct defects.
  lines.push(
    `Findings by dimension: ${Object.entries(summary.byDimension).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}`,
  );
  lines.push('');

  lines.push('## Distinct defects');
  lines.push('');
  lines.push(
    'Grouped by subject, because several rules can detect the same underlying bug. ORD-1010 trips three rules from one transposition; counting that as three defects would overstate the result. Where more than one rule fires, that is corroboration - two independent checks reaching the same conclusion.',
  );
  lines.push('');
  lines.push('| # | Case | Severity | Detected by | Dimensions |');
  lines.push('|---|---|---|---|---|');
  groupByRootCause(defects).forEach((group, index) => {
    lines.push(
      `| ${index + 1} | ${escapePipes(group.cases.join(', '))} | ${group.severity} | ${group.ruleIds.join(' + ')}${group.corroborated ? ` (${group.findings.length} rules agree)` : ''} | ${group.dimensions.join(', ')} |`,
    );
  });
  lines.push('');

  lines.push('## Every finding');
  lines.push('');
  lines.push('| ID | Case(s) | Severity | Dimension | Rule violated |');
  lines.push('|---|---|---|---|---|');
  defects.forEach((finding, index) => {
    lines.push(
      `| D-${String(index + 1).padStart(2, '0')} | ${escapePipes(finding.cases.join(', '))} | ${finding.severity} | ${finding.dimension} | ${escapePipes(finding.title)} (${finding.ruleId}) |`,
    );
  });
  lines.push('');

  lines.push('## Findings in detail');
  lines.push('');
  defects.forEach((finding, index) => {
    lines.push(`### D-${String(index + 1).padStart(2, '0')} - ${finding.cases.join(', ')} - ${finding.title}`);
    lines.push('');
    lines.push(`**Severity** ${finding.severity} | **Dimension** ${finding.dimension} | **Rule** \`${finding.ruleId}\``);
    lines.push('');
    lines.push(finding.summary);
    lines.push('');
    lines.push(`**Contract clause violated**  \n> ${finding.contract}`);
    lines.push('');
    lines.push(`**How it was detected**  \n${finding.detection}`);
    lines.push('');
    const evidence = evidenceBlock(finding.evidence);
    if (evidence) {
      lines.push('**Evidence**');
      lines.push('```');
      lines.push(evidence);
      lines.push('```');
      lines.push('');
    }
  });

  if (observations.length) {
    lines.push('## Observations - not counted as defects');
    lines.push('');
    lines.push(
      `Not counted as defects. LATE-DELIVERY is a business finding: the sync copied both dates correctly. STALE-LAST-MODIFIED is outside the contract and needs confirming; where it fires on an order that already has a defect (${corroborated.join(', ') || 'none'}) it is corroboration, not a new finding.`,
    );
    lines.push('');
    lines.push('| ID | Case(s) | Observation |');
    lines.push('|---|---|---|');
    observations.forEach((finding, index) => {
      lines.push(`| O-${String(index + 1).padStart(2, '0')} | ${finding.cases.join(', ')} | ${escapePipes(finding.summary)} |`);
    });
    lines.push('');
  }

  lines.push('## Rule inventory');
  lines.push('');
  lines.push('Every rule that ran, including the ones that found nothing. A rule finding nothing is evidence of coverage; a dimension with no rule is a blind spot.');
  lines.push('');
  lines.push('| Rule | Dimension | Scope | Severity | Checks |');
  lines.push('|---|---|---|---|---|');
  const raisedById = new Map(result.executed.map((e) => [e.id, e.raised]));
  for (const rule of allRules) {
    lines.push(
      `| \`${rule.id}\` | ${rule.dimension} | ${rule.scope} | ${rule.severity} | ${escapePipes(rule.title)} — raised ${raisedById.get(rule.id) ?? 0} |`,
    );
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
};
