import { allRules } from '../rules/index.js';
import { groupByRootCause } from './engine.js';

const escapePipes = (value) => String(value).replace(/\|/g, '\\|');

const evidenceBlock = (evidence) =>
  Object.entries(evidence)
    .filter(([, value]) => value !== null && value !== undefined && value !== '')
    .map(([key, value]) => `  ${key}: ${Array.isArray(value) ? value.join(' -> ') : value}`)
    .join('\n');

/**
 * The report is generated from the same run that produces the console output, so the document can
 * never drift from the code. A hand-maintained defect report is a second source of truth and the
 * first thing to go stale.
 */
export const renderDefectReport = (result) => {
  const { summary, defects, observations, model } = result;
  const lines = [];

  lines.push('# Defect Report - OMS to Analytics sync');
  lines.push('');
  lines.push(`Generated by \`npm run reconcile -- --write-report\` at ${model.now.toISOString()}.`);
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| Source rows | ${model.counts.orders} orders |`);
  lines.push(`| Target rows | ${model.counts.events} events across ${model.counts.cases} cases |`);
  lines.push(`| Rules executed | ${summary.ruleCount} |`);
  lines.push(
    `| Defects | **${summary.distinctDefects} distinct** (${summary.ruleViolations} rule violations) across ${summary.affectedCases.length} cases |`,
  );
  lines.push(`| Observations (not defects) | ${summary.observationCount} |`);
  lines.push(`| Rules that errored | ${summary.erroredRules} |`);
  lines.push('');
  lines.push(
    `Severity: ${Object.entries(summary.bySeverity).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}`,
  );
  lines.push('');
  lines.push(
    `Dimensions: ${Object.entries(summary.byDimension).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}`,
  );
  lines.push('');

  lines.push('## Distinct defects');
  lines.push('');
  lines.push(
    'Grouped by subject, because several rules can detect the same underlying bug. ORD-1010 trips three rules from one transposition; counting that as three defects would overstate the result. Where more than one rule fires, that is corroboration - two independent checks reaching the same conclusion.',
  );
  lines.push('');
  lines.push('| # | Case | Severity | Detected by | Dimensions |');
  lines.push('|---|---|---|---|---|');
  groupByRootCause(defects).forEach((group, index) => {
    lines.push(
      `| ${index + 1} | ${escapePipes(group.cases.join(', '))} | ${group.severity} | ${group.ruleIds.join(' + ')}${group.corroborated ? ` (${group.findings.length} rules agree)` : ''} | ${group.dimensions.join(', ')} |`,
    );
  });
  lines.push('');

  lines.push('## Every rule violation');
  lines.push('');
  lines.push('| ID | Case(s) | Severity | Dimension | Rule violated |');
  lines.push('|---|---|---|---|---|');
  defects.forEach((finding, index) => {
    lines.push(
      `| D-${String(index + 1).padStart(2, '0')} | ${escapePipes(finding.cases.join(', '))} | ${finding.severity} | ${finding.dimension} | ${escapePipes(finding.title)} (${finding.ruleId}) |`,
    );
  });
  lines.push('');

  lines.push('## Findings in detail');
  lines.push('');
  defects.forEach((finding, index) => {
    lines.push(`### D-${String(index + 1).padStart(2, '0')} - ${finding.cases.join(', ')} - ${finding.title}`);
    lines.push('');
    lines.push(`**Severity** ${finding.severity} | **Dimension** ${finding.dimension} | **Rule** \`${finding.ruleId}\``);
    lines.push('');
    lines.push(finding.summary);
    lines.push('');
    lines.push(`**Contract clause violated**  \n> ${finding.contract}`);
    lines.push('');
    lines.push(`**How it was detected**  \n${finding.detection}`);
    lines.push('');
    const evidence = evidenceBlock(finding.evidence);
    if (evidence) {
      lines.push('**Evidence**');
      lines.push('```');
      lines.push(evidence);
      lines.push('```');
      lines.push('');
    }
  });

  if (observations.length) {
    lines.push('## Observations - behaving as specified, reported for information');
    lines.push('');
    lines.push(
      'These are not integration defects. The sync reproduced both sides faithfully; the finding is about the business process. They are listed separately so the defect count stays honest.',
    );
    lines.push('');
    lines.push('| ID | Case(s) | Observation |');
    lines.push('|---|---|---|');
    observations.forEach((finding, index) => {
      lines.push(`| O-${String(index + 1).padStart(2, '0')} | ${finding.cases.join(', ')} | ${escapePipes(finding.summary)} |`);
    });
    lines.push('');
  }

  lines.push('## Rule inventory');
  lines.push('');
  lines.push('Every rule that ran, including the ones that found nothing. A rule finding nothing is evidence of coverage; a dimension with no rule is a blind spot.');
  lines.push('');
  lines.push('| Rule | Dimension | Scope | Severity | Checks |');
  lines.push('|---|---|---|---|---|');
  const raisedById = new Map(result.executed.map((e) => [e.id, e.raised]));
  for (const rule of allRules) {
    lines.push(
      `| \`${rule.id}\` | ${rule.dimension} | ${rule.scope} | ${rule.severity} | ${escapePipes(rule.title)} — raised ${raisedById.get(rule.id) ?? 0} |`,
    );
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
};
